PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?itemLabel ?predicate ?relatedItemLabel
WHERE {
  VALUES ?practiceLabelString { "sustainable soil management"@en "soil protection"@en }
  ?practice skos:prefLabel ?practiceLabelString ;
            skos:prefLabel ?itemLabel .
  FILTER(LANG(?itemLabel) = "en")

  ?practice ?predicate ?targetOfPractice .
  FILTER(?predicate = obo:T4FS_0000577)

  ?targetOfPractice skos:prefLabel ?relatedItemLabel .
  FILTER(LANG(?relatedItemLabel) = "en")
}

ORDER BY ?itemLabel ?predicate ?relatedItemLabel