PREFIX she: <https://soilwise-he.github.io/soil-health#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?resultType ?value
WHERE {
  ?degradation skos:prefLabel "soil degradation"@en .

  {
    ?degradation skos:definition ?value .
    BIND("Definition" AS ?resultType)
  }
  UNION
  {
    ?degradation she:isIndicatedBy ?indicator .
    ?indicator skos:prefLabel ?value .
    BIND("Indicator" AS ?resultType)
  }
}

ORDER BY ?resultType