PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX biolink: <https://w3id.org/biolink/vocab/>

SELECT ?subjectLabel ?predicateURI ?objectLabel
WHERE {
  {
    she:LandTake skos:prefLabel ?ltLabel_def .
    she:LandTake skos:definition ?definition .
    BIND(?ltLabel_def AS ?subjectLabel)
    BIND(skos:definition AS ?predicateURI)
    BIND(?definition AS ?objectLabel)
  }
  UNION
  {
    she:LandTake skos:prefLabel ?ltLabel_consumes_rural .
    she:LandTake sio:SIO_000210 ?indicatorNode .
    ?indicatorNode biolink:consumes ?ra .
    ?ra skos:prefLabel ?raLabel .
    BIND(?ltLabel_consumes_rural AS ?subjectLabel)
    BIND(biolink:consumes AS ?predicateURI)
    BIND(?raLabel AS ?objectLabel)
  }
}
ORDER BY ?subjectLabel ?predicateURI ?objectLabel