PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>
PREFIX bao: <http://www.bioassayontology.org/bao#>
PREFIX agrontology: <http://aims.fao.org/aos/agrontology#>
PREFIX schema: <https://schema.org/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX af-x: <http://purl.allotrope.org/ontologies/property#>

SELECT ?itemDescription ?relationshipOrProperty ?valueDescription
WHERE {
  {
    ?indicator bao:BAO_0002586 ?assessmentNode .

    ?assessmentNode agrontology:isUsedIn she:AgriculturalSoils .
    she:AgriculturalSoils skos:prefLabel ?agriSoilsLabel .

    ?assessmentNode schema:assesses ?assessedUri .
    ?assessedUri skos:prefLabel ?assessedConceptLabel .
    ?indicator skos:prefLabel ?indicatorLabel .

    BIND(?indicatorLabel AS ?itemDescription)
    BIND(bao:BAO_0002586 AS ?relationshipOrProperty)
    BIND(CONCAT("assessment of ", ?assessedConceptLabel, " in ", ?agriSoilsLabel) AS ?valueDescription)
  }
  UNION
  {
    she:pH skos:prefLabel ?phLabel .
    she:pH agrontology:smallerThan ?conditionNode .

    ?conditionNode agrontology:causes she:AluminiumRelease .
    she:AluminiumRelease skos:prefLabel ?alReleaseLabel .

    ?conditionNode af-x:AFX_0000408 she:AgriculturalSoils .
    she:AgriculturalSoils skos:prefLabel ?agriSoilsContextLabel .

    ?conditionNode qudt:numericValue ?phValue .

    BIND(?phLabel AS ?itemDescription)
    BIND(agrontology:smallerThan AS ?relationshipOrProperty)
    BIND(CONCAT(STR(?phValue), " (causes ", ?alReleaseLabel, " in ", ?agriSoilsContextLabel, ")") AS ?valueDescription)
  }
}
ORDER BY ?itemDescription ?relationshipOrProperty