PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?itemLabel ?predicate ?relatedItemLabel
WHERE {
  VALUES ?practiceLabelString { "sustainable soil management"@en "soil protection"@en }
  ?practice skos:prefLabel ?practiceLabelString ;
            skos:prefLabel ?itemLabel .

  ?practice ?predicate ?targetOfPractice .
  FILTER(?predicate = obo:T4FS_0000577)

  ?targetOfPractice skos:prefLabel ?relatedItemLabel .
}

ORDER BY ?itemLabel ?predicate ?relatedItemLabel