PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>
PREFIX bao: <http://www.bioassayontology.org/bao#>
PREFIX agrontology: <http://aims.fao.org/aos/agrontology#>

SELECT ?subjectLabel ?predicateURI ?objectLabel
WHERE {
  {
    she:SoilErosionByWater skos:prefLabel ?sebwLabel .
    she:SoilErosionByWater bao:BAO_0095002 ?slr .
    ?slr skos:prefLabel ?slrLabel .

    BIND(?sebwLabel AS ?subjectLabel)
    BIND(bao:BAO_0095002 AS ?predicateURI)
    BIND(?slrLabel AS ?objectLabel)
  }
  UNION
  {
    she:SoilErosionSubindicator skos:prefLabel ?sesiLabel .
    she:SoilErosionSubindicator agrontology:includes ?subIndicator .
    ?subIndicator skos:prefLabel ?subIndicatorLabel .

    BIND(?sesiLabel AS ?subjectLabel)
    BIND(agrontology:includes AS ?predicateURI)
    BIND(?subIndicatorLabel AS ?objectLabel)
  }
}
ORDER BY ?subjectLabel ?predicateURI ?objectLabel