PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>
PREFIX agrontology: <http://aims.fao.org/aos/agrontology#>

SELECT ?subjectLabel ?predicateURI ?objectLabel
WHERE {
  {
    she:SoilSalinisation skos:prefLabel ?ssLabel_broader .
    she:SoilSalinisation skos:broader ?sdp .
    ?sdp skos:prefLabel ?sdpLabel .
    BIND(?ssLabel_broader AS ?subjectLabel)
    BIND(skos:broader AS ?predicateURI)
    BIND(?sdpLabel AS ?objectLabel)
  }
  UNION
  {
    she:SoilSalinisation skos:prefLabel ?ssLabel_fertility .
    she:SoilSalinisation ?rela she:SoilFertility .
    she:SoilFertility skos:prefLabel ?sfLabel .
    BIND(?ssLabel_fertility AS ?subjectLabel)
    BIND(?rela AS ?predicateURI)
    BIND(?sfLabel AS ?objectLabel)
  }
  UNION
  {
    she:SoilSalinisation skos:prefLabel ?ssLabel_nf .
    she:SoilSalinisation agrontology:isCausedBy ?nf .
    ?nf skos:prefLabel ?nfLabel .
    BIND(?ssLabel_nf AS ?subjectLabel)
    BIND(agrontology:isCausedBy AS ?predicateURI)
    BIND(?nfLabel AS ?objectLabel)
  }
}
ORDER BY ?subjectLabel ?predicateURI ?objectLabel