PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>

SELECT ?subjectLabel ?predicateURI ?objectLabel
WHERE {
  {
    she:DiffusePollutedSites skos:prefLabel ?dpsLabel .
    she:DiffusePollutedSites she:isCharacterisedBy ?hppConcept .
    ?hppConcept skos:prefLabel ?hppLabel .

    BIND(?dpsLabel AS ?subjectLabel)
    BIND(she:isCharacterisedBy AS ?predicateURI)
    BIND(?hppLabel AS ?objectLabel)
  }
  UNION
  {
    ?dpsApp skos:prefLabel ?lsLabel .
    ?dpsApp she:appliesTo she:DiffusePollutedSites .
    she:DiffusePollutedSites skos:prefLabel ?dpsLabel_ls .

    BIND(?lsLabel AS ?subjectLabel)
    BIND(she:appliesTo AS ?predicateURI)
    BIND(?dpsLabel_ls AS ?objectLabel)
  }
  UNION
  {
    ?investigationType she:appliesTo she:PointSourcePollutedSites .
    ?investigationType skos:prefLabel ?investigationTypeLabel .
    she:PointSourcePollutedSites skos:prefLabel ?pspsLabel .

    BIND(?investigationTypeLabel AS ?subjectLabel)
    BIND(she:appliesTo AS ?predicateURI)
    BIND(?pspsLabel AS ?objectLabel)
  }
}
ORDER BY ?subjectLabel ?predicateURI ?objectLabel