PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>
PREFIX agrontology: <http://aims.fao.org/aos/agrontology#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?subjectLabel ?predicateURI ?objectLabel
WHERE {
  {
    she:SoilSalinisation skos:prefLabel ?ssLabel .
    she:SoilSalinisation skos:definition ?ssDefinition .
    BIND(?ssLabel AS ?subjectLabel)
    BIND(skos:definition AS ?predicateURI)
    BIND(?ssDefinition AS ?objectLabel)
  }
  UNION
  {
    she:Sodification skos:prefLabel ?sodLabel .
    she:Sodification skos:definition ?sodDefinition .
    BIND(?sodLabel AS ?subjectLabel)
    BIND(skos:definition AS ?predicateURI)
    BIND(?sodDefinition AS ?objectLabel)
  }
  UNION
  {
    she:Sodification skos:prefLabel ?sodLabel_phys .
    she:Sodification agrontology:causes ?usp .
    ?usp skos:prefLabel ?uspLabel .
    BIND(?sodLabel_phys AS ?subjectLabel)
    BIND(agrontology:causes AS ?predicateURI)
    BIND(?uspLabel AS ?objectLabel)
  }
  UNION
  {
    she:Sodification agrontology:causes ?usp .
    ?usp skos:prefLabel ?uspLabel_esp .
    ?usp obo:RO_0002212 ?esp .
    ?esp skos:prefLabel ?espLabel_phys .
    BIND(?uspLabel_esp AS ?subjectLabel)
    BIND(obo:RO_0002212 AS ?predicateURI)
    BIND(?espLabel_phys AS ?objectLabel)
  }
  UNION
  {
    she:Sodification agrontology:causes ?usp .
    ?usp skos:prefLabel ?uspLabel_esp .
    ?usp obo:RO_0002552 ?soil .
    ?soil skos:prefLabel ?soilLabel_phys .
    BIND(?uspLabel_esp AS ?subjectLabel)
    BIND(obo:RO_0002552 AS ?predicateURI)
    BIND(?soilLabel_phys AS ?objectLabel)
  }
}
ORDER BY ?subjectLabel ?predicateURI ?objectLabel