PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?indicatorLabel ?relationshipProperty ?relatedItemLabelOrURI
WHERE {
  {
    she:SoilBiodiversityIndicators skos:narrower ?indicatorURI .
    ?indicatorURI skos:prefLabel ?indicatorLabel_val .
    ?indicatorURI dcterms:source ?sourceURI .
    VALUES ?sourceURI { she:Breure2004 she:Huber2008 }
    OPTIONAL { ?sourceURI skos:prefLabel ?sourceLabel_opt . }
    BIND(COALESCE(?sourceLabel_opt, STR(?sourceURI)) AS ?sourceDisplay) .

    BIND(?indicatorLabel_val AS ?indicatorLabel)
    BIND(dcterms:source AS ?relationshipProperty)
    BIND(?sourceDisplay AS ?relatedItemLabelOrURI)
  }
}
ORDER BY ?indicatorLabel ?relationshipProperty ?relatedItemLabelOrURI