PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>
PREFIX agrontology: <http://aims.fao.org/aos/agrontology#>
PREFIX schema: <https://schema.org/>
PREFIX af-x: <http://purl.allotrope.org/ontologies/property#>
PREFIX sio: <http://semanticscience.org/resource/>

SELECT ?subjectLabel ?predicateURI ?objectLabel
WHERE {
  {
    she:Level1SoilErosionMonitoring skos:prefLabel ?l1semLabel .
    she:Level1SoilErosionMonitoring agrontology:includes ?lsm .
    ?lsm skos:prefLabel ?lsmLabel .
    BIND(?l1semLabel AS ?subjectLabel)
    BIND(agrontology:includes AS ?predicateURI)
    BIND(?lsmLabel AS ?objectLabel)
  }
  UNION
  {
    she:Level1SoilErosionMonitoring skos:prefLabel ?l1semLabel .
    she:Level1SoilErosionMonitoring agrontology:includes ?lsm .
    ?lsm skos:prefLabel ?lsmLabel_assess_sl .
    ?lsm schema:assesses ?slrbw .
    ?slrbw skos:prefLabel ?slrbwLabel .
    BIND(?lsmLabel_assess_sl AS ?subjectLabel)
    BIND(schema:assesses AS ?predicateURI)
    BIND(?slrbwLabel AS ?objectLabel)
  }
  UNION
  {
    she:Level1SoilErosionMonitoring skos:prefLabel ?l1semLabel_hs .
    she:Level1SoilErosionMonitoring af-x:AFX_0002717 ?sehs .
    ?sehs skos:prefLabel ?sehsLabel_l1 .
    BIND(?l1semLabel_hs AS ?subjectLabel)
    BIND(af-x:AFX_0002717 AS ?predicateURI)
    BIND(?sehsLabel_l1 AS ?objectLabel)
  }
  UNION
  {
    she:Level2SoilErosionMonitoring skos:prefLabel ?l2semLabel .
    she:Level2SoilErosionMonitoring agrontology:includes ?ma .
    ?ma skos:prefLabel ?maLabel_l2 .
    BIND(?l2semLabel AS ?subjectLabel)
    BIND(agrontology:includes AS ?predicateURI)
    BIND(?maLabel_l2 AS ?objectLabel)
  }
  UNION
  {
    she:Level2SoilErosionMonitoring skos:prefLabel ?l2semLabel .
    she:Level2SoilErosionMonitoring agrontology:includes ?ma .
    ?ma skos:prefLabel ?maLabel_gt .
    ?ma sio:SIO_000365 ?gtd .
    ?gtd skos:prefLabel ?gtdLabel .
    BIND(?maLabel_gt AS ?subjectLabel)
    BIND(sio:SIO_000365 AS ?predicateURI)
    BIND(?gtdLabel AS ?objectLabel)
  }
  UNION
  {
    she:Level2SoilErosionMonitoring skos:prefLabel ?l2semLabel .
    she:Level2SoilErosionMonitoring agrontology:includes ?ma .
    ?ma skos:prefLabel ?maLabel_sfsm .
    ?ma agrontology:makeUseOf ?sfsm .
    ?sfsm skos:prefLabel ?sfsmLabel .
    BIND(?maLabel_sfsm AS ?subjectLabel)
    BIND(agrontology:makeUseOf AS ?predicateURI)
    BIND(?sfsmLabel AS ?objectLabel)
  }
  UNION
  {
    she:Level2SoilErosionMonitoring skos:prefLabel ?l2semLabel .
    she:Level2SoilErosionMonitoring agrontology:includes ?ma .
    ?ma skos:prefLabel ?maLabel_scale .
    ?ma af-x:AFX_0000408 ?scale .
    ?scale skos:prefLabel ?scaleLabel .
    BIND(?maLabel_scale AS ?subjectLabel)
    BIND(af-x:AFX_0000408 AS ?predicateURI)
    BIND(?scaleLabel AS ?objectLabel)
  }
  UNION
  {
    she:Level2SoilErosionMonitoring skos:prefLabel ?l2semLabel .
    she:Level2SoilErosionMonitoring agrontology:includes ?ma .
    ?ma skos:prefLabel ?maLabel_focus .
    ?ma she:focusesOn ?alp .
    ?alp skos:prefLabel ?alpLabel .
    BIND(?maLabel_focus AS ?subjectLabel)
    BIND(she:focusesOn AS ?predicateURI)
    BIND(?alpLabel AS ?objectLabel)
  }
  UNION
  {
    ?sehs skos:prefLabel ?sehsLabel_l2 .
    ?sehs agrontology:isUsedIn she:Level2SoilErosionMonitoring .
    she:Level2SoilErosionMonitoring skos:prefLabel ?l2semLabel_hs .
    BIND(?sehsLabel_l2 AS ?subjectLabel)
    BIND(agrontology:isUsedIn AS ?predicateURI)
    BIND(?l2semLabel_hs AS ?objectLabel)
  }
}
ORDER BY ?subjectLabel ?predicateURI ?objectLabel