PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>
PREFIX agrontology: <http://aims.fao.org/aos/agrontology#>

SELECT ?subjectLabel ?predicateURI ?objectLabel
WHERE {
    she:SoilEcologicalFunctions skos:prefLabel ?esfLabel_includes .
    she:SoilEcologicalFunctions agrontology:includes ?specificFunction .
    ?specificFunction skos:prefLabel ?specificFunctionLabel .

    BIND(?esfLabel_includes AS ?subjectLabel)
    BIND(agrontology:includes AS ?predicateURI)
    BIND(?specificFunctionLabel AS ?objectLabel)
}
ORDER BY ?subjectLabel ?predicateURI ?objectLabel