PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX agrontology: <http://aims.fao.org/aos/agrontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX af-x: <http://purl.allotrope.org/ontologies/property#>

SELECT ?subjectLabel ?predicateURI ?objectLabel
WHERE {
  {
    she:SaturatedHydraulicConductivity skos:prefLabel ?shcLabel .
    she:SaturatedHydraulicConductivity sio:SIO_000210 ?functionalQualitySHC .
    ?functionalQualitySHC skos:prefLabel ?fqLabelSHC .

    BIND(?shcLabel AS ?subjectLabel)
    BIND(sio:SIO_000210 AS ?predicateURI)
    BIND(?fqLabelSHC AS ?objectLabel)
  }
  UNION
  {
    she:UnsaturatedHydraulicConductivity skos:prefLabel ?uhcLabel .
    she:UnsaturatedHydraulicConductivity sio:SIO_000210 ?functionalQualityUHC .
    ?functionalQualityUHC skos:prefLabel ?fqLabelUHC .

    BIND(?uhcLabel AS ?subjectLabel)
    BIND(sio:SIO_000210 AS ?predicateURI)
    BIND(?fqLabelUHC AS ?objectLabel)
  }
  UNION
  {
    she:AirPermeability skos:prefLabel ?apLabel .
    she:AirPermeability sio:SIO_000210 ?functionalQualityAP .
    ?functionalQualityAP skos:prefLabel ?fqLabelAP .

    BIND(?apLabel AS ?subjectLabel)
    BIND(sio:SIO_000210 AS ?predicateURI)
    BIND(?fqLabelAP AS ?objectLabel)
  }
  UNION
  {
    she:SaturatedHydraulicConductivity skos:prefLabel ?shcLabel_smp .
    she:SaturatedHydraulicConductivity obo:RO_0002502 ?smp .
    ?smp skos:prefLabel ?smpLabel .

    BIND(?shcLabel_smp AS ?subjectLabel)
    BIND(obo:RO_0002502 AS ?predicateURI)
    BIND(?smpLabel AS ?objectLabel)
  }
  UNION
  {
    she:UnsaturatedHydraulicConductivity skos:prefLabel ?shcLabel_smp .
    she:UnsaturatedHydraulicConductivity obo:RO_0002502 ?smp .
    ?smp skos:prefLabel ?smpLabel .

    BIND(?shcLabel_smp AS ?subjectLabel)
    BIND(obo:RO_0002502 AS ?predicateURI)
    BIND(?smpLabel AS ?objectLabel)
  }
  UNION
  {
    she:AirPermeability skos:prefLabel ?shcLabel_smp .
    she:AirPermeability obo:RO_0002502 ?smp .
    ?smp skos:prefLabel ?smpLabel .

    BIND(?shcLabel_smp AS ?subjectLabel)
    BIND(obo:RO_0002502 AS ?predicateURI)
    BIND(?smpLabel AS ?objectLabel)
  }
  UNION
  {
    ?parameterForTrafficability agrontology:isUsedIn ?bnode_traffic .
    ?bnode_traffic obo:RO_0002508 ?trafficability .
    ?parameterForTrafficability skos:prefLabel ?pftLabel .
    ?trafficability skos:prefLabel ?trafficabilityLabel .

    BIND(?pftLabel AS ?subjectLabel)
    BIND(obo:RO_0002508 AS ?predicateURI)
    BIND(?trafficabilityLabel AS ?objectLabel)
  }
  UNION
  {
    ?uhcap skos:prefLabel ?uhcLabel_flux .
    ?uhcap agrontology:measures ?bnode_uhc_flux .
    ?bnode_uhc_flux rdf:object ?fluxes .
    ?fluxes skos:prefLabel ?fluxesLabel_uhc .
    ?bnode_uhc_flux af-x:AFX_0000408 ?pd .
    ?pd skos:prefLabel ?pdLabel_uhc .

    BIND(?uhcLabel_flux AS ?subjectLabel)
    BIND(agrontology:measures AS ?predicateURI)
    BIND(?fluxesLabel_uhc AS ?objectLabel)
  }
}
ORDER BY ?subjectLabel ?predicateURI ?objectLabel