PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX she: <https://soilwise-he.github.io/soil-health#>

SELECT ?subjectLabel ?predicateURI ?objectLabel
WHERE {
  {
    she:SoilErosion skos:prefLabel ?seLabel_main .
    she:SoilErosion skos:narrower ?mainErosionType .
    ?mainErosionType skos:prefLabel ?mainErosionTypeLabel .

    BIND(?seLabel_main AS ?subjectLabel)
    BIND(skos:narrower AS ?predicateURI)
    BIND(?mainErosionTypeLabel AS ?objectLabel)
  }
  UNION
  {
    she:SoilErosion skos:prefLabel ?seLabel_main .
    she:SoilErosion skos:narrower ?mainErosionType .
    ?mainErosionType skos:prefLabel ?mainErosionTypeLabel .
    ?mainErosionType skos:narrower ?subtype .
    ?subtype skos:prefLabel ?subtypeLabel .
    BIND(?mainErosionTypeLabel AS ?subjectLabel)
    BIND(skos:narrower AS ?predicateURI)
    BIND(?subtypeLabel AS ?objectLabel)
  }
}
ORDER BY ?subjectLabel ?predicateURI ?objectLabel